### ISSUE TITLE
Airline name for Lufthansa is Lufthansa Cargo

### ISSUE THREAD

**Issue by btbbass** [xavierguihot/geobase#3]
Hi, 

with the latest airline data (optd_airlines.csv)
(here a commit on the file, that add the airline type to both LHs)
https://github.com/opentraveldata/opentraveldata/commit/60de441f4a5aa23711d3c1a43e4f03a8bdece53c#diff-21a1e584a64bab94a2395ce3b2bb267d )

this test fail:

[info] - Airline to airline name *** FAILED *** (12 milliseconds)
[info]   Success("Lufthansa Cargo") did not equal Success("Lufthansa") (GeoBaseTest.scala:179)

In this case, Lufthansa and Lufthansa Cargo shares the same LH code, but the library cannot really handle this situation, as the loader put the airlines in a map;
I think that as they share the same key, the first one that come is overwritten by the second one (or maybe it is the first that persist)
Anyway, I think that some other filtering should be put in place (maybe airline type ? ) in order to keep only the wanted airline, or handle the case of multiple airlines with the same code.

**Comment by xavierguihot** [comment]
Hi,

Indeed, open travel data's `optd_airlines.csv` can provide several names for a given airline code (240 out of the 1470 airline iata codes have at least 2 associated names).

I'm naively choosing the first name out of the list of possible names, which was good enough for our requirements.

Apparently, `LH`'s names have been updated making this particular test fail and making the lib choose `Lufthansa Cargo` rather than `Lufthansa`.

I've included a list of exceptions to the "choose first to come" rule with for now `LH` only. Haven't been through the full list of airlines to look for obvious miss choices though.

I've created https://github.com/xavierguihot/geobase/pull/5. Let me know if that's good for you.

**Comment by xavierguihot** [comment]
I merged https://github.com/xavierguihot/geobase/pull/5 into master and created release [2.0.1](https://github.com/xavierguihot/geobase/releases/tag/2.0.1).

**Comment by btbbass** [comment]
Hi, 
thanks a lot for the fix.

I think this is a good short term solution, but for the long term (v 3.0 maybe :-) ) a more general logic should be implemented. Maybe just checking the airline creation date (I think it should be present in the data) and returning the oldest one, so that an exception list has not to be maintained ( that can become painful )

**Comment by xavierguihot** [comment]
Yes, I really don't like the hardcoded exception list I've implemented.
I'll check if a set of rules exists from the dataset itself to avoid it.
Not sure if taking the oldest airline name is the best bet though.
